name: Deploy Shiny App

on:
  push:
    branches:
      - main
      - "4-dashboard-development-using-shiny"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: "4.4.2"

      - name: Install R packages
        run: |
          R -e 'install.packages(c("rsconnect"))'
          R -e 'rsconnect::setAccountInfo(name="${{ secrets.SHINYAPPS_USER }}", token="${{ secrets.SHINYAPPS_TOKEN }}", secret="${{ secrets.SHINYAPPS_SECRET }}")'
          R -e 'rsconnect::deployApp("./", appName="DSViz_Project")'
