name: Deploy Shiny App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: "4.3.3"

      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2

      - name: Export cleaned data
        run: |
          mkdir 'data/cleaned_data'
          R -e 'source("cleaning.R")'

      - name: Deploy Shiny App
        run: |
          R -e 'rsconnect::setAccountInfo(name="${{ secrets.SHINYAPPS_USER }}", token="${{ secrets.SHINYAPPS_TOKEN }}", secret="${{ secrets.SHINYAPPS_SECRET }}")'
          R -e 'rsconnect::deployApp("./", appName="DSViz_Project", forceUpdate=TRUE, appFiles=c("app.R", "helper.R", list.files("data/cleaned_data", full.names=TRUE, recursive=TRUE)))'

      - name: Convert to Shinylive
        run: |
          mkdir 'shinylive'
          R -e 'shinylive::export(appdir="./", destdir="./shinylive/")'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.PA_TOKEN }}
          branch: gh-pages
          folder: shinylive
