name: Deploy Shiny App

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pages: write

jobs:
  deploy-shiny:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: "4.4.1"

      - name: Install terra dependencies (https://github.com/rspatial/terra)
        run: |
          sudo apt-get -y update && sudo apt-get install -y  libudunits2-dev libgdal-dev libgeos-dev libproj-dev

      - name: Install R Dependencies (renv)
        uses: r-lib/actions/setup-renv@v2

      - name: Export cleaned data
        run: |
          mkdir 'data/cleaned_data'

          R -e '
          YEARS <- c("2018", "2019", "2020", "2021", "2022", "2023")
          BASE_PATH <- "."
          source("cleaning.R")
          '

      - name: Deploy Shiny App
        run: |
          R -e '
          rsconnect::setAccountInfo(name="${{ secrets.SHINYAPPS_USER }}", token="${{ secrets.SHINYAPPS_TOKEN }}", secret="${{ secrets.SHINYAPPS_SECRET }}")
          rsconnect::deployApp("./", appName="DSViz_Project", forceUpdate=TRUE, appFiles=c("app.R", "helper.R", list.files("data/cleaned_data", full.names=TRUE, recursive=TRUE)))
          '

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          tinytex: true

      - name: Render and Publish
        id: github-pages
        uses: quarto-dev/quarto-actions/publish@v2.1.6
        with:
          target: gh-pages
          path: report
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
